
export const API_CONFIG = {
  BASE_URL: 'http://localhost:8081/api',
  ENDPOINTS: {
    LOGIN: '/auth/login',
    TEMPLE_DANA_ASSIGNMENTS: '/temple-dana-assignment/by-family-ids',
    CONFIRM_ASSIGNMENT: '/temple-dana-assignment/conform',
    MEMBER: '/member',
    ASSIGNMENTS_BY_FAMILY: '/temple-dana-assignment/family',
    ASSIGNMENTS_BY_DATE: '/temple-dana-assignment/date',
    ASSIGNMENTS_BY_MEMBER: '/temple-dana-assignment/by-member',
    TEMPLE_DANA: '/temple-dana/temple',
    DANA_TYPES: '/dana',
    ASSIGN_DANA: '/temple-dana/assign',
    HELPER: '/helper',
    HELPER_BY_TEMPLE: '/helper/temple',
    MEMBER_BY_FAMILY: '/member/by-family',
    MEMBER_BY_TEMPLE: '/member/by-temple',
    MEMBER_BY_VILLAGE: '/member/by-village',
    MEMBER_BY_PHONE: '/member/by-phone',
    FAMILY: '/family',
    FAMILY_BY_TEMPLE: '/family/by-temple',
    FAMILY_BY_VILLAGE: '/family/by-village',
    ASSIGN_MEMBERS_TO_FAMILY: '/family/assign-members',
    ASSIGN_MEMBERS_TO_FAMILY_AT_ONCE: '/family/assign-members-at-once',
    TEMPLE_VILLAGE_BY_TEMPLE: '/temple-village/by-temple',
    TEMPLE_VILLAGE_ASSIGN: '/temple-village/assign-village',
    TEMPLE: '/temple',
    VILLAGE: '/village',
    VILLAGE_BY_TEMPLE: '/village/temple',
    VILLAGE_FILTER: '/village/filter',
    HEAD_MONK: '/head-monk',
    HEAD_MONK_BY_TEMPLE: '/head-monk/temple',
  }
};
